failfast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ffb6a759a979008c0e6dff86e39f4745a2d9eac4 # frozen: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/crate-ci/typos
    rev: b1ae8d918b6e85bd611117d3d9a3be4f903ee5e4 # frozen: v1.33.1
    hooks:
      - id: typos

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 8543de60614be13db6cd7d27b8a236a78dc436e9 # frozen: 0.33.1
    hooks:
      - id: check-renovate
