failfast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 6fd1ced85fc139abd7f5ab4f3d78dab37592cd5e # frozen: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier

  - repo: https://github.com/crate-ci/typos
    rev: b1ae8d918b6e85bd611117d3d9a3be4f903ee5e4 # frozen: v1.33.1
    hooks:
      - id: typos

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: fd9dcbefa7f0e094e02841e992489e8b9d394f8a # frozen: 0.23.1
    hooks:
      - id: check-renovate
